export const API_CONFIG = {
  BASE_URL: process.env.REACT_APP_API_URL,
  AUTH_ENDPOINT: process.env.REACT_APP_AUTH_ENDPOINT,
  DOCS_ENDPOINT: process.env.REACT_APP_DOCS_ENDPOINT,
  USE_MOCKS: true,
};
